version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cv_evaluator
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    restart: always
    ports:
      - '8000:8000'

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
